workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      groups:
        - firebase_credentials
      vars:
        PACKAGE_NAME: "br.com.yson.listacompras"
      node: latest
    scripts:
      - name: Set up local.properties
        script: |
          # Encontra onde está o arquivo build.gradle.kts
          BUILD_FILE=$(find . -name "build.gradle.kts" | head -n 1)
          PROJECT_DIR=$(dirname "$BUILD_FILE")
          if [ "$(basename "$PROJECT_DIR")" = "app" ]; then
            PROJECT_DIR=$(dirname "$PROJECT_DIR")
          fi
          cd "$PROJECT_DIR"
          
          # Cria o arquivo exigido pelo Android SDK e dá permissão ao executor
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          chmod +x gradlew
      - name: Build Android APK
        script: |
          BUILD_FILE=$(find . -name "build.gradle.kts" | head -n 1)
          PROJECT_DIR=$(dirname "$BUILD_FILE")
          if [ "$(basename "$PROJECT_DIR")" = "app" ]; then
            PROJECT_DIR=$(dirname "$PROJECT_DIR")
          fi
          cd "$PROJECT_DIR"
          
          # Executa a compilação direta usando o arquivo gradlew que você criou
          ./gradlew assembleDebug
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
