workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      groups:

        - assinatura
      vars:
        PACKAGE_NAME: "br.com.yson.listacompras"
      node: latest
    scripts:
      - name: Configurar e Compilar Projeto
        script: |
          # Transforma o texto Base64 de volta no arquivo de chave físico
          echo $CM_KEYSTORE | base64 --decode > /tmp/lista_compras.jks
          export CM_KEYSTORE_PATH="/tmp/lista_compras.jks"

          # Configura o SDK e força a permissão de execução do gradlew no servidor
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          chmod +x gradlew # ➕ ADICIONE ESTA LINHA EXATAMENTE AQUI

          # Compila o pacote .aab da loja
          ./gradlew bundleRelease
    artifacts:
      - "**/build/outputs/bundle/**/*.aab"
          

